volumes:
  aria2:
    name: aria2
    driver_opts:
      type: none
      o: bind
      device: ${ARIA2_DATA_DIR}
  music:
    name: music
    driver_opts:
      type: none
      o: bind
      device: ${MUSIC_DATA_DIR}
  qbittorrent:
    name: qbittorrent
    driver_opts:
      type: none
      o: bind
      device: ${QBITTORRENT_DATA_DIR}
  jellyfin:
    name: jellyfin
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.docker/volumes/jellyfin