services:
  jellyfin:
    image: "ghcr.io/jellyfin/jellyfin:12.0"
    container_name: "jellyfin"
    hostname: "jellyfin"
    volumes:
      - "./config/jellyfin:/config"
      - "./cache:/cache"
      - "jellyfin:/media/jellyfin"
      - "qbittorrent:/media/qbittorrent"
    restart: 'unless-stopped'
    ports:
      - "8096:8096"
    depends_on:
      - metatube
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      NO_PROXY: localhost,127.0.0.1,metatube,metatube:8080
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

  metatube:
    image: "ghcr.io/metatube-community/metatube-server:dev"
    container_name: "metatube"
    hostname: "metatube"
    restart: 'unless-stopped'
    volumes:
      - ./config/metatube:/config
    environment:
      HTTP_PROXY: http://host.docker.internal:7890
      HTTPS_PROXY: http://host.docker.internal:7890
      MT_MOVIE_PROVIDER_JAVBUS__PRIORITY: 1100
    command:
      - "-dsn"
      - "/config/metatube.db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"

volumes:
  jellyfin:
    name: jellyfin
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.docker/volumes/jellyfin

  qbittorrent:
    name: qbittorrent
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.docker/volumes/qbittorrent